[theme]
base = "light"
primaryColor = "#17665E"
backgroundColor = "#F6F7F4"
secondaryBackgroundColor = "#E9EEE8"
textColor = "#172D2A"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
maxUploadSize = 2
